### Site Settings ###
title               : mumsens.se
description         : >-
                      Hi! I am Mats Magnusson. Welcome to my homepage.  
                      I am full stack developer, but my preference is
                      front-end with JavaScript.
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : Massemania/Massemania.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : #YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html


### Author Info ###
author:
  name              : Mats Magnusson
  image             : https://media-exp1.licdn.com/dms/image/C5603AQHuXwr_XhnTxw/profile-displayphoto-shrink_200_200/0?e=1590624000&v=beta&t=dsyuwsndP08qdmQ_M7ZmIRysfF9vxcjh20uuYWGYBE4
# behance           : your_username
# dribbble          : your_username
  email             : mats.magnusson@comhem.se
  facebook          : mats.magnusson
  github            : Massemania
# gitlab            : your_username
# instagram         : your_username
  linkedin          : matsmagnusson1
  medium            : Massemania
# soundcloud        : your_username
  spotify           : Massemania
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : Massemania
# vimeo             : your_username
# youtube           : your_channel_name
# phone             : +46760070599



### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"

### Github meta data error fix ###
github: [metadata]